spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/worldcupstats
    username: worldcupuser
    password: worldcuppassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
